// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.crinali.www.archprot.domain;

import it.crinali.www.archprot.domain.Contatto;

privileged aspect Contatto_Roo_JavaBean {
    
    public String Contatto.getEmail() {
        return this.email;
    }
    
    public void Contatto.setEmail(String email) {
        this.email = email;
    }
    
}
