// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.crinali.www.archprot.domain;

import it.crinali.www.archprot.domain.Note;

privileged aspect Note_Roo_JavaBean {
    
    public String Note.getTesto() {
        return this.testo;
    }
    
    public void Note.setTesto(String testo) {
        this.testo = testo;
    }
    
}
