// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.crinali.www.archprot.domain;

import it.crinali.www.archprot.domain.TipoComunicazione;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoComunicazione_Roo_Configurable {
    
    declare @type: TipoComunicazione: @Configurable;
    
}
